language: node_js
node_js:
  - "0.11"

install:
  - npm install

env:
  global:
    - secure: "SNOWHArQYU/zvLyr5uA72QUskkTkOPYtV07h0rWYe0Pnw6pnFLIqiKfLkfnp7wkDthP43IMD33ftvJBrHHZCbUZPCCKHzI8MYEGKCgX6eUCrFmkGZ+qljykZCGFB0YA3VGlL2rGH2P1b73gYpjVeH/so8maYHJA3tUCopU9wtQk="

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # - ./node_modules/protractor/bin/webdriver-manager update --standalone
  # - node scripts/web-server.js &
  # - ./node_modules/protractor/bin/webdriver-manager start &

script:
  - grunt test:travis
