language: node_js

sudo: false

node_js:
  - "0.10"

env:
  global:
  - PROTRACTOR_BROWSERS=firefox
  - KARMA_BROWSERS=Firefox,PhantomJS
  - secure: "NwL+WhB/vBbs3eTXrtp+18apGigtrVZEnP03+9cJeBHFfY27Rmy2J4VT6TilnYDYBqOiE+BDIszOFJo/cSx0buXd4ca5jlPcojNvipYiOXEp0RP+jLBUBXYPo7ocgwWI7xk2mIbdqgS1EXr0Fyr9nmFArriYThvSiXRsLN5Zs6s="

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - peons test --reporter=spec

after_success:
  - peons coveralls
